### ISSUE TITLE
Evaluate CMS admin panels

### ISSUE THREAD

**Issue by mgottholsen** [civicdata/civicdata.github.io#39]
There are a few different options for Jekyll admin panels, it may behoove us to find one for regular content editing for users. It's problematic for some users that may not be familiar with Git(Hub) yet, but can still contribute content.

Thoughts?

**Comment by mgottholsen** [comment]
Here are a few options I found in a quick pass, please add any others you may find.

Jekyll Admin - localhost
https://github.com/jekyll/jekyll-admin

Siteleaf - Paid w/ free tier
https://www.siteleaf.com/

Datocms - Paid w/ free tier
https://www.datocms.com/cms/jekyll/

Netlify 
https://www.netlify.com/blog/2015/10/28/a-step-by-step-guide-jekyll-3.0-on-netlify/

Forestry.io
https://forestry.io/

**Comment by mgottholsen** [comment]
Evaluation Matrix - Once we get a good list, we can use a matrix to determine the best fit.

|Service | Cost        | Usability           | Features  |
| ------------- |:-------------:| -----:|------------:|
| Jekyll Admin|||
| Sitelead|||
| Datocms || |
|Netlify|||
|Forestry.io|||

**Comment by cheapwebmonkey** [comment]
Idk that CMS panels are necessary at this juncture. I would like to hear comments on why people might feel a CMS is necessary.

I have evaluated all of these, in the past,  and many only allow the commits/merges to happen in master, which is not best practice for version control, so those would be ruled out on that basis. If we decide to implement a CMS, we will need one that allows proper version control branching/merging, as we do not directly touch master, well, ever.

I think there was one, siteleaf maybe, (maybe not) that did not function in this manner, but cost was associated with that one.

**Comment by jessetylermullins** [comment]
Agree that a CMS has to have proper version control. If it does that, then it lowers barriers to non-devs (or people unfamiliar with Git(Hub)) to create content for us. Right now a non-dev would need to create their content and then pass to someone who knows how to format it and fork/branch/PR/merge it, so it's more labor by more people.

**Comment by thebouv** [comment]
Since the content of the site is Markdown, is the only technical barrier some non-dev people who want to contribute content don't understand GitHub?

A few questions:

1)  Who are these non-dev people?  Are they real, as in they said they want to contribute but cannot due to the barrier?  Or are they hypothetical at this juncture?

2)  If they are non-dev, but want to learn, isn't the barrier solvable by teaching?  At the end of the day we are a "mostly hi tech" organization.

3)  We have to consider the technical debt versus the technical gain we get from adding a CMS.  The new debt is:  the CMS we choose itself is a piece of software that needs maintenance (feature patches, security patches, etc).  In consideration, there may be 9 technical people who are comfortable with editing content in MD files and pushing to branches, etc.  And 1 non-technical person who finds a barrier.  If those were real numbers, I wouldn't make the decision to add a CMS at this point.  If we have many non-tech people clamoring to assist with content for the site, I'd be more likely to see the value.

Just looking at this from the lense of "on paper it sounds like it adds value, but let's step back and make sure we're solving a real problem".

**Comment by cheapwebmonkey** [comment]
To speak to @thebouv's question, re non-technical contributors, if they exist, I am unaware of anyone who wishes to add content who is unable to leverage Markdown and GitHub

If we are speaking, in theory, about new Code Louisville students, I think we should probably be guiding them in learning the dev way to edit the project, vs adding the technical debt of a CMS, as adding to people's civic tech skillset and education is part of our mission statement.

**Comment by mgottholsen** [comment]
Sounds good!
