### ISSUE TITLE
Discuss "Jekyll per repo" idea

### ISSUE THREAD

**Issue by mgottholsen** [civicdata/civicdata.github.io#45]
The basic idea would be to have a slim version of jekyll setup for designated content repos. These would feed content to the main site whenever they were regenerated, through a json feed file.

Discuss pros/cons

Immediate con: Adds to dev/ops work. Could be alleviated through automation.

**Comment by mgottholsen** [comment]
This also feeds into general content operations, how content is managed etc.

**Comment by jessetylermullins** [comment]
I like the idea theoretically but so far it might add more technical debt than necessary. We need to be forking the main repo and creating feature branches. I'm interested to hear thoughts on how dev/ops workload increase can be alleviated through automation.

Also - this idea would make issue #39 moot, correct? No need for a CMS admin panel if we're updating everything via ancillary repos.

**Comment by jessetylermullins** [comment]
Maybe #39 isn't moot if we use a CMS that has a JSON API like Siteleaf.

**Comment by mgottholsen** [comment]
@thebouv So here's the idea in it's entirety.

We have a lot of different repos, that all have content that *should* contribute to the main website.

 - Branding
 - CDA Wiki
 - Meeting Minutes
 - Blog
 - Etc

The idea is to setup a slim Jekyll build, that only has one layout for generating JSON. The core of the idea is that whenever that content/repo is updated, it automatically triggers a build from GitHub pages, refreshing the feed.

The other end of this idea, is that the main CDA website would have some vanilla javascript in it's Jekyll theme that would render that content to the main site.

There are a few different benefits to this approach, and a few different constraints.

*Benefits:*
 - You don't have to do duplicate work of creating content in two places (origin repo, main site repo)
 - You get individual git histories of each repo of content
 - The person that owns the content, also is able to curate that content, distributing site content responsibility 
 - You can have entirely different management processes (different teams, approval flows, project boards)  around each repo that matches that content. 
 

*Constraints:*
 - Content repo maintainer needs to be familiar with Jekyll
 - Each repo needs to be technically maintained (gems, security etc)

Thoughts, anyone else?

**Comment by leighPri** [comment]
I'm still willing to try this but I wonder if we don't just shift the content into the existing site repo and maintain it there? Jekyll does folders pretty well already, after all, so things could still be organized

Meeting minutes, for example, was set up with GitHub reading in mind, but it's a one-time effort to switch it to match the site and then not difficult to maintain after the fact.

I realize that this gives the potential headache of making sure your HEAD is at the right point and we'll have to be more careful not to override others' work but I think it would end up at the same place work-wise potentially with less complexity.

I defer to someone with actual Jekyll experience, of course, but that's my current thought.

**Comment by jessetylermullins** [comment]
The benefits listed seem like differences without benefit. If someone forks/branches/PRs the main repo and it gets merged, that seems like the same amount of work as fork/branch/PR the ancillary repo. I think it also dilutes the amount of traffic on the main repo via `insights` as well - which could potentially detrimental depending on our goals. As far as history goes, if we have a simple labeling structure (following the workflow + project/feature name) we can isolate that history if we need to. If there's more value in having the separate git histories, please correct me there - I'm still learning.

Also, we can have multiple project boards on this repo - which would consolidate the work going on which makes the delivery leads life easier. Otherwise it's navigating through each individual repo to see what's going on. I'm more of a fan of consolidating it and creating a robust repo with a dense history - it gives anyone contributing more of a real experience with org-scale projects.

I think the technical maintenance and the increase in a need for familiarity with systems is more technical debt than the benefits alleviate.

**Comment by jessetylermullins** [comment]
That being said, I would be in favor of seeing a test case, or selecting an individual project for proof-of-concept as long as we have people to maintain it. It's an interesting idea!

**Comment by cheapwebmonkey** [comment]
I agree with Leigh

You do not use your deployed live site for the proof of concept, science project, imo. That is dirty lol
