### ISSUE TITLE
Add webmention support?

### ISSUE THREAD

**Issue by mgottholsen** [civicdata/civicdata.github.io#51]
Do we want to add webmention support? Should be pretty trivial.

Resources:
https://indieweb.org/Webmention
https://github.com/w3c/webmention (draft spec)

https://github.com/aarongustafson/jekyll-webmention_io (Jekyll plugin)
https://webmention.io/

**Comment by thebouv** [comment]
Do we want to have conversations on our site?

That we also have to dedicated eyes to moderating?

Which leads me to wondering what the gains vs pains are for this feature.

Easy to implement code-wise it seems because of that Jekyll plugin, but I worry about the labor debt on maintaining moderation.  I can think of a few souls who would love to abuse it anonymously.

**Comment by mgottholsen** [comment]
I think a lot of that depends on the implementation.

Just webmention_count, likes or links is what I'm thinking. Specifically on the blog pages.

**Comment by mgottholsen** [comment]
Why don't I create a branch and we can check it out, although I need to verify if it's supported by Github Pages...

**Comment by mgottholsen** [comment]
Closing issue.
